RustboroCity_MoveTutorFlat_2F_MapScripts::
	.byte 0


RustboroCity_MoveTutorFlat_2F_EventScript_Mother::
	msgbox RustboroCity_MoveTutorFlat_2F_Text_MyFamilyIsCrazy, MSGBOX_NPC
	end

RustboroCity_MoveTutorFlat_2F_EventScript_Daughter::
	msgbox RustboroCity_MoveTutorFlat_2F_Text_IllGetYou, MSGBOX_NPC
	end

RustboroCity_MoveTutorFlat_2F_EventScript_Sister::
	msgbox RustboroCity_MoveTutorFlat_2F_Text_Giggle, MSGBOX_NPC
	end

RustboroCity_MoveTutorFlat_2F_Text_MyFamilyIsCrazy::	
	.string "In all the hustle and bustle of the city\n"
	.string "It is sometimes very hard to take care\l"
	.string "of your family.\p"
	.string "Especially if they drive you crazy.$"

RustboroCity_MoveTutorFlat_2F_Text_IllGetYou::
	.string "Watch out! I'm coming to get you!$"

RustboroCity_MoveTutorFlat_2F_Text_Giggle::
	.string "Giggle!$"
